
networks:
  proxy_traefik:

services:
  minecraft:
    image: itzg/minecraft-server
    networks:
      proxy_traefik:
    ports:
      - 25565:25565
      - 8082:8100
    environment:
      EULA: "true"
      TYPE: PAPER
      VERSION: 1.20.6
      INIT_MEMORY: 1G
      MAX_MEMORY: 1G
      MODRINTH_PROJECTS: bluemap
      MODRINTH_ALLOWED_VERSION_TYPE: release
      MAX_PLAYERS: 1
    volumes:
      - ./data/minecraft/bluemap:/data/plugins/BlueMap
    labels:
      - traefik.enable=true
      - traefik.http.routers.mc1206paper.rule=Host(`127.0.0.1`)
      - traefik.http.routers.mc1206paper.entrypoints=web
      - traefik.http.services.mc1206paper.loadbalancer.server.port=8100

  traefik:
    image: traefik:2.11
    restart: unless-stopped
    ports:
      - "8080:80"
      - "127.0.0.1:8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik:/etc/traefik
    networks:
      proxy_traefik:
      
  whoami:
    image: traefik/whoami
    restart: unless-stopped
    depends_on:
      - traefik
    networks:
      proxy_traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: PathPrefix(`/whoami`)
      traefik.http.routers.whoami.priority: 100
      traefik.http.routers.whoami.entrypoints: web
      traefik.http.routers.whoami.middlewares: stripprefix-whoami
      traefik.http.middlewares.stripprefix-whoami.stripprefix.prefixes: /whoami